version: '3'
services:

  server:
    build: ./app.py
    ports:
      - 5000:3000
    links:
      - db
    depends_on:
      - db
    environment:
      - app.py

  db:
    image: 
      - sqlite3:../flaskr/database.db
    volumes:

volumes:
  db:
    driver: local
  server:
    driver: local